const textPools = {
thai: [
    "ฉันกำลังพิมพ์ข้อความอย่างรวดเร็ว",
    "การฝึกทุกวันช่วยให้พัฒนา",
    "ความสำเร็จไม่ได้เกิดขึ้นในชั่วข้ามคืน",
    "อย่าหยุดเมื่อเหนื่อยแต่หยุดเมื่อสำเร็จ",
    "วันนี้เป็นวันที่สดใส",
    "การเริ่มต้นคือครึ่งหนึ่งของความสำเร็จ",
    "ฉันชอบเรียนรู้สิ่งใหม่ทุกวัน",
    "โลกเต็มไปด้วยโอกาสมากมาย",
    "ความพยายามไม่เคยทรยศใคร",
    "ทุกก้าวเล็กๆมีความหมาย",
    "การคิดบวกช่วยให้มีความสุข",
    "เสียงลมพัดเบาๆในยามเย็น",
    "ดอกไม้กำลังบานอย่างสวยงาม",
    "ฉันชอบดูพระอาทิตย์ตกดิน",
    "การวางแผนช่วยให้งานสำเร็จง่ายขึ้น",
    "ชีวิตเต็มไปด้วยบทเรียน",
    "ทุกคนมีความสามารถในแบบของตนเอง",
    "ความหวังคือพลังในการก้าวต่อไป",
    "ฉันกำลังสร้างอนาคตของตัวเอง",
    "การแบ่งปันทำให้สังคมน่าอยู่",
    "แสงจันทร์ส่องสว่างในคืนมืด",
    "การเรียนรู้ไม่มีขีดจำกัด",
    "ความฝันจะเป็นจริงเมื่อกล้าลงมือทำ",
    "การช่วยเหลือผู้อื่นเป็นเรื่องที่ดี",
    "ฉันชอบใช้เวลาอยู่กับครอบครัว",
    "ทุกวันคือการเริ่มต้นใหม่",
    "ความรับผิดชอบเป็นคุณสมบัติที่สำคัญ",
    "การทำงานหนักย่อมเห็นผล",
    "ความคิดสร้างสรรค์เกิดจากการฝึกฝน",
    "ฉันชอบเดินเล่นท่ามกลางธรรมชาติ",
    "ท้องฟ้าในวันนี้สดใสเป็นพิเศษ",
    "การอ่านหนังสือช่วยเปิดมุมมองใหม่",
    "ไม่มีอะไรยากเกินความพยายาม",
    "จงกล้าที่จะเปลี่ยนแปลงตัวเอง",
    "ความสุขเริ่มต้นจากใจที่พอเพียง",
    "ฉันกำลังฝึกฝนทักษะใหม่",
    "ทุกปัญหาคือบทเรียนที่มีค่า",
    "ความมุ่งมั่นนำไปสู่ความสำเร็จ",
    "อย่ากลัวที่จะล้มเหลว",
    "การลงมือทำสำคัญกว่าการคิดเพียงอย่างเดียว",
    "แมวสีส้มกำลังนอนหลับ",
    "เด็กชายกำลังขี่จักรยาน",
    "ตลาดเช้ามีผู้คนคึกคัก",
    "รถไฟกำลังออกจากสถานี",
    "นักเรียนกำลังตั้งใจเรียน",
    "ภูเขาสูงตระหง่านอยู่ไกลออกไป",
    "ทะเลกว้างใหญ่สวยงามมาก",
    "เสียงคลื่นซัดเข้าหาฝั่ง",
    "ต้นไม้เขียวขจีหลังฝนตก",
    "ฝนตกโปรยปรายตลอดทั้งคืน"
  ],

  english: [
    "The quick brown fox jumps over the lazy dog",
    "Success is built one step at a time",
    "Every day brings a new opportunity",
    "Never stop improving yourself",
    "Practice is the key to mastery",
    "Hard work always pays off",
    "Learning new things is exciting",
    "The stars look beautiful tonight",
    "I enjoy spending time with my family",
    "The weather feels pleasant today",
    "Small actions create big changes",
    "Confidence grows through experience",
    "The journey is just as important as the destination",
    "Always keep an open mind",
    "Patience is a valuable skill",
    "The river flows through the valley",
    "Reading books expands the imagination",
    "A positive attitude makes a difference",
    "Every challenge teaches a lesson",
    "Dreams become reality through effort",
    "The birds are singing in the morning",
    "The garden is full of colorful flowers",
    "Technology changes the world every day",
    "The students are working together",
    "A healthy lifestyle improves well being",
    "The mountain view is breathtaking",
    "The sound of rain is relaxing",
    "I enjoy learning foreign languages",
    "The future starts with today's decisions",
    "Kindness can brighten someone's day",
    "The city looks beautiful at night",
    "Teamwork helps achieve difficult goals",
    "The airplane disappeared into the clouds",
    "The teacher explained the topic clearly",
    "The athlete trains every single day",
    "The computer processes information quickly",
    "The library is a place of knowledge",
    "Every mistake is a chance to learn",
    "Success requires dedication and discipline",
    "The road ahead is full of possibilities",
    "The cat is sleeping near the window",
    "The children are playing happily outside",
    "The sunset painted the sky orange",
    "The coffee smells wonderful this morning",
    "Music can change your mood instantly",
    "The project was completed successfully",
    "The forest is calm and peaceful",
    "A smile can make someone's day better",
    "The train arrived exactly on time",
    "Knowledge grows when it is shared"
  ]
};